### ISSUE TITLE
Using Docker container name

### ISSUE THREAD

**Issue by K-Michallik** [UniversalRobots/Universal_Robots_ExternalControl_URCapX#1]
https://github.com/UniversalRobots/Universal_Robots_ExternalControl_URCapX/blob/3a2048d1c69b6fc04e2f15c965a9cde1d75fcbef/README.md?plain=1#L62

As you have named your container, it may be easier to just reference the container's name directly when following the logs instead of the ID (ID's are subject to change which makes to user have to call `docker ps` frequently).

You can simply type the following to get the logs every time:
`docker logs -f universal-robots_external-control_external-control-backend`

**Comment by urrsk** [comment]
@K-Michallik thanks
